### PR TITLE
Update components page

### PR DESCRIPTION
**Pull request by HaSistrunk**
- Add links to dimes and rac-schemas repos
- Adjust component page heading levels

### CODE REVIEW

**Comment by helrond** [comment]
Wondering if it makes sense to have a heading structure something like this:
```
RFCs
Transfer Applications
  Aurora
  API Gateway and microservices
Archival Discovery
  DIMES
  Request Broker
  Cartographer
  Data Pipeline
Libraries
```

**Comment by HaSistrunk** [comment]
That heading structure makes good sense to me, thanks. I've updated with that approach. I also added the iiif pipeline - does that make sense to have in libraries (or should I move it to the data pipeline section)?

**Comment by helrond** [comment]
This is perfect (and good catch on the IIIF Pipeline)!

**Review by helrond — APPROVED** [review]
Great! Thanks for catching the IIIF pipeline too.

**Pull request merged**
